name: Docker-Image bauen und veröffentlichen

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    name: Docker-Image bauen und pushen
    runs-on: ubuntu-latest

    # Berechtigungen für das Hochladen des Pakets geben
    permissions:
      contents: read
      packages: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: In GitHub Container Registry einloggen
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker-Metadaten extrahieren
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Docker-Image bauen und pushen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.exports.labels }}
