name: Testen und Bericht committen

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-commit-report:
    name: Testen und Bericht committen
    runs-on: ubuntu-latest

     
    # DIESEN BLOCK HINZUFÜGEN
    permissions:
      contents: write

    steps:
      # 1. Code auschecken (unverändert)
      - name: Code auschecken
        uses: actions/checkout@v4

      # 2. Python einrichten (unverändert)
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Abhängigkeiten installieren (unverändert)
      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt

      # 4. HTML-Bericht erstellen (unverändert)
      - name: Pytest ausführen und HTML-Bericht erstellen
        run: pytest --html=report.html --self-contained-html

      # 5. NEU: Den erstellten Bericht ins Repository committen
      - name: HTML-Bericht ins Repository committen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Automatisch generierten Testbericht hinzufügen"
          file_pattern: report.html